### ISSUE TITLE
Your version of touch deletes the file

### ISSUE THREAD

**Issue by tamusjroyce** [remarkablemark/remarkablemark.github.io#1]
Of: https://remarkablemark.org/blog/2017/12/17/touch-file-nodejs/

Please replace

```
const fs = require('fs');
const filename = 'file.txt';
fs.closeSync(fs.openSync(filename, 'w'));
```
with boutell solution below
```
const fs = require('fs');
var now = new Date();
const filename = 'file.txt';
fs.utimesSync(filename, now, now);
```
to prevent the contents of the file from being blanked out. That way it follows posix touch.

You might even combine them, per below:

```
const fs = require('fs');
var now = new Date();
const filename = 'file.txt';
try {
  fs.utimesSync(filename, now, now); // Update last modified date
} catch (ex) {
  fs.closeSync(fs.openSync(filename, 'w'));
}
```

**Comment by remarkablemark** [comment]
Thanks for opening this issue @tamusjroyce. [boutell's solution](http://disq.us/p/21rurrt) does seem much better. Would you be interested in making a PR?

**Comment by tamusjroyce** [comment]
I'm not quite sure how. It's just the first hit I get when searching this. Thank you for taking notice!

**Comment by remarkablemark** [comment]
No worries @tamusjroyce, I updated the post. Thanks once again for bringing this to my attention!
